// Package server implements an SFTP server. It is designed to run
// as an SSH subsystem: the caller establishes an SSH channel for
// the "sftp" subsystem and hands it to Serve.
//
// The server maintains no state of its own; all filesystem
// operations are delegated to a Backend implementation. A simple
// OS-backed backend is provided in the osfs sub-package.
package server

import (
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"os"
	"sync"
	"time"

	"github.com/natalie-o-perret/go-sftp/sftp"
)

// FileHandle is an opaque identifier issued by the backend to
// represent an open file. The handle is generated by the server
// and opaque to the client.
type FileHandle string

// FileStat is the minimum file metadata the server needs to
// return to the client. A backend can fill only the fields it
// knows about.
type FileStat struct {
	Name  string
	Size  uint64
	Mode  uint32
	IsDir bool
	Mtime int64
	UID   uint32
	GID   uint32
}

// Backend is the filesystem interface the server calls. All paths
// are absolute and rooted at the server's chroot. Implementations
// are responsible for sandboxing; the server does not interpret
// paths.
type Backend interface {
	Stat(path string) (FileStat, error)
	Lstat(path string) (FileStat, error)
	Open(path string, flags uint32) (FileHandle, error)
	Read(handle FileHandle, offset uint64, data []byte) (int, error)
	Write(handle FileHandle, offset uint64, data []byte) (int, error)
	Close(handle FileHandle) error
	Readdir(path string) ([]FileStat, error)
	Mkdir(path string) error
	Rmdir(path string) error
	Remove(path string) error
	Rename(from, to string) error
}

// Server is an SFTP server bound to a single connection.
type Server struct {
	backend Backend
}

// New constructs a Server.
func New(backend Backend) *Server { return &Server{backend: backend} }

// Serve runs the server on ch. It blocks until either side closes
// the channel or an unrecoverable protocol error occurs.
func (s *Server) Serve(ch io.ReadWriteCloser) error {
	init, err := sftp.ReadPacket(ch)
	if err != nil {
		return err
	}
	if init.Type != sftp.TypeInit {
		return fmt.Errorf("sftp: expected INIT, got %d", init.Type)
	}
	ver, err := sftp.ReadInit(init)
	if err != nil {
		return err
	}
	if ver.Version != sftp.Version {
		return fmt.Errorf("sftp: unsupported client version %d", ver.Version)
	}
	if err := sftp.WritePacket(ch, sftp.TypeVersion, sftp.AppendUint32(nil, sftp.Version)); err != nil {
		return err
	}
	var (
		mu       sync.Mutex
		handles  = map[FileHandle]FileHandle{}
		drained  = map[FileHandle]bool{}
		nextID   uint32
	)
	newHandle := func(real FileHandle) FileHandle {
		mu.Lock()
		defer mu.Unlock()
		nextID++
		h := FileHandle(fmt.Sprintf("h%d", nextID))
		handles[h] = real
		return h
	}
	resolve := func(h FileHandle) (FileHandle, error) {
		mu.Lock()
		defer mu.Unlock()
		real, ok := handles[h]
		if !ok {
			return "", fmt.Errorf("invalid handle")
		}
		return real, nil
	}
	markDrained := func(h FileHandle) {
		mu.Lock()
		defer mu.Unlock()
		drained[h] = true
	}
	isDrained := func(h FileHandle) bool {
		mu.Lock()
		defer mu.Unlock()
		return drained[h]
	}
	drop := func(h FileHandle) {
		mu.Lock()
		defer mu.Unlock()
		delete(handles, h)
		delete(drained, h)
	}
	for {
		pkt, err := sftp.ReadPacket(ch)
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
		if len(pkt.Payload) < 4 {
			continue
		}
		id := sftp.RequestID(binary.BigEndian.Uint32(pkt.Payload[:4]))
		rest := pkt.Payload[4:]
		switch pkt.Type {
		case sftp.TypeOpen:
			path, off, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			pFlags, _, err := sftp.ReadUint32(rest, off)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			real, err := s.backend.Open(path, pFlags)
			if err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			h := newHandle(real)
			payload := sftp.AppendUint32(nil, uint32(id))
			payload = sftp.AppendString(payload, string(h))
			sftp.WritePacket(ch, sftp.TypeHandle, payload)
		case sftp.TypeClose:
			h, _, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			real, err := resolve(FileHandle(h))
			if err != nil {
				s.sendStatus(ch, id, sftp.StatusFailure, err)
				continue
			}
			s.backend.Close(real)
			drop(FileHandle(h))
			s.sendStatus(ch, id, sftp.StatusOK, "")
		case sftp.TypeRead:
			h, off, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			offset, off, err := sftp.ReadUint64(rest, off)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			size, _, err := sftp.ReadUint32(rest, off)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			real, err := resolve(FileHandle(h))
			if err != nil {
				s.sendStatus(ch, id, sftp.StatusFailure, err)
				continue
			}
			buf := make([]byte, size)
			n, err := s.backend.Read(real, offset, buf)
			if err == io.EOF {
				s.sendStatus(ch, id, sftp.StatusEOF, "")
				continue
			}
			if err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			payload := sftp.AppendUint32(nil, uint32(id))
			payload = sftp.AppendUint32(payload, uint32(n))
			payload = append(payload, buf[:n]...)
			sftp.WritePacket(ch, sftp.TypeData, payload)
		case sftp.TypeWrite:
			h, off, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			offset, off, err := sftp.ReadUint64(rest, off)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			data, off, err := sftp.ReadString(rest, off)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			real, err := resolve(FileHandle(h))
			if err != nil {
				s.sendStatus(ch, id, sftp.StatusFailure, err)
				continue
			}
			_, err = s.backend.Write(real, offset, []byte(data))
			if err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			s.sendStatus(ch, id, sftp.StatusOK, "")
		case sftp.TypeStat:
			path, _, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			st, err := s.backend.Stat(path)
			if err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			s.sendAttrs(ch, id, st)
		case sftp.TypeLstat:
			path, _, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			st, err := s.backend.Lstat(path)
			if err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			s.sendAttrs(ch, id, st)
		case sftp.TypeOpendir:
			path, _, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			_, err = s.backend.Readdir(path)
			if err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			// We don't actually keep a server-side directory handle;
			// the handle is just a marker. Readdir is a snapshot.
			real := FileHandle("dir:" + path)
			h := newHandle(real)
			payload := sftp.AppendUint32(nil, uint32(id))
			payload = sftp.AppendString(payload, string(h))
			sftp.WritePacket(ch, sftp.TypeHandle, payload)
		case sftp.TypeReaddir:
			h, _, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			if isDrained(FileHandle(h)) {
				s.sendStatus(ch, id, sftp.StatusEOF, "")
				continue
			}
			real, err := resolve(FileHandle(h))
			if err != nil {
				s.sendStatus(ch, id, sftp.StatusFailure, err)
				continue
			}
			path := string(real)[4:] // strip "dir:" prefix
			entries, err := s.backend.Readdir(path)
			if err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			payload := sftp.AppendUint32(nil, uint32(id))
			for _, e := range entries {
				payload = sftp.AppendString(payload, e.Name)
				payload = sftp.AppendString(payload, "")
				a := sftp.FileAttr{Size: e.Size, UID: e.UID, GID: e.GID, Mode: e.Mode}
				if e.Mtime != 0 {
					a.Mtime = time.Unix(e.Mtime, 0)
				}
				payload = append(payload, a.Encode()...)
			}
			sftp.WritePacket(ch, sftp.TypeName, payload)
			markDrained(FileHandle(h))
		case sftp.TypeMkdir:
			path, _, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			if err := s.backend.Mkdir(path); err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			s.sendStatus(ch, id, sftp.StatusOK, "")
		case sftp.TypeRmdir:
			path, _, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			if err := s.backend.Rmdir(path); err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			s.sendStatus(ch, id, sftp.StatusOK, "")
		case sftp.TypeRemove:
			path, _, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			if err := s.backend.Remove(path); err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			s.sendStatus(ch, id, sftp.StatusOK, "")
		case sftp.TypeRename:
			from, off, err := sftp.ReadString(rest, 0)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			to, _, err := sftp.ReadString(rest, off)
			if err != nil {
				return s.sendStatus(ch, id, sftp.StatusBadMessage, err)
			}
			if err := s.backend.Rename(from, to); err != nil {
				s.sendStatus(ch, id, mapErr(err), err.Error())
				continue
			}
			s.sendStatus(ch, id, sftp.StatusOK, "")
		default:
			s.sendStatus(ch, id, sftp.StatusOpUnsupported, "unsupported")
		}
	}
}

func (s *Server) sendStatus(ch io.Writer, id sftp.RequestID, code sftp.StatusCode, msg interface{}) error {
	m := ""
	if msg != nil {
		if s, ok := msg.(string); ok {
			m = s
		} else if e, ok := msg.(error); ok {
			m = e.Error()
		}
	}
	return sftp.WritePacket(ch, sftp.TypeStatus, sftp.EncodeStatus(id, code, m, ""))
}

func (s *Server) sendAttrs(ch io.Writer, id sftp.RequestID, st FileStat) error {
	payload := sftp.AppendUint32(nil, uint32(id))
	a := sftp.FileAttr{Size: st.Size, UID: st.UID, GID: st.GID, Mode: st.Mode}
	if st.Mtime != 0 {
		a.Mtime = time.Unix(st.Mtime, 0)
	}
	payload = append(payload, a.Encode()...)
	return sftp.WritePacket(ch, sftp.TypeAttrs, payload)
}

func mapErr(err error) sftp.StatusCode {
	if err == nil {
		return sftp.StatusOK
	}
	if errors.Is(err, os.ErrNotExist) {
		return sftp.StatusNoSuchFile
	}
	if errors.Is(err, os.ErrPermission) {
		return sftp.StatusPermissionDenied
	}
	return sftp.StatusFailure
}
